version: "3.9"

services:
  fastapi_service:
    build:
      context: ./app
      dockerfile: Dockerfile
    hostname: fastapi_service
    container_name: fastapi_service
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    volumes:
      - ./app:/home/app
    networks:
      - my-net

  cache-redis:
    image: redis:alpine
    hostname: cache-redis
    container_name: cache-redis
    restart: on-failure
    ports:
      - '6379:6379'
    expose:
      - '6379'
    command: redis-server
    volumes:
      - cache:/data
    networks:
      - my-net

  db_postgres:
    image: postgres:14.3-alpine
    hostname: db_postgres
    container_name: db_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    networks:
      - my-net

volumes:
  db-postgres:
    driver: local

  cache:
    driver: local

networks:
  my-net:
    external: true